/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package myapp;

import org.apache.commons.net.ftp.FTPClient;

/**
 *
 * @author Adam */

        public class MyAppGui extends javax.swing.JFrame {

    /**
     * Creates new form MyAppGui
     */
    public MyAppGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DesktopPane1 = new javax.swing.JDesktopPane();
        InternalFrameLogin = new javax.swing.JInternalFrame();
        ButtonCancel = new javax.swing.JButton();
        TextFieldFtpAddress = new javax.swing.JTextField();
        MenuBar = new javax.swing.JMenuBar();
        Menu1 = new javax.swing.JMenu();
        MenuItemConnect = new javax.swing.JMenuItem();
        Separator = new javax.swing.JPopupMenu.Separator();
        MenuItemExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        InternalFrameLogin.setVisible(false);

        ButtonCancel.setText("Cancel");

        TextFieldFtpAddress.setText("ftp://");

        javax.swing.GroupLayout InternalFrameLoginLayout = new javax.swing.GroupLayout(InternalFrameLogin.getContentPane());
        InternalFrameLogin.getContentPane().setLayout(InternalFrameLoginLayout);
        InternalFrameLoginLayout.setHorizontalGroup(
            InternalFrameLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InternalFrameLoginLayout.createSequentialGroup()
                .addGroup(InternalFrameLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InternalFrameLoginLayout.createSequentialGroup()
                        .addContainerGap(259, Short.MAX_VALUE)
                        .addComponent(ButtonCancel))
                    .addGroup(InternalFrameLoginLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(TextFieldFtpAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        InternalFrameLoginLayout.setVerticalGroup(
            InternalFrameLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InternalFrameLoginLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(TextFieldFtpAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(ButtonCancel)
                .addContainerGap())
        );

        InternalFrameLogin.setBounds(230, 70, 350, 210);
        DesktopPane1.add(InternalFrameLogin, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Menu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Gnome-Network-Idle-32.png"))); // NOI18N
        Menu1.setText("Menu");

        MenuItemConnect.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        MenuItemConnect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Gnome-Preferences-System-Network-32.png"))); // NOI18N
        MenuItemConnect.setText("Connect");
        MenuItemConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemConnectActionPerformed(evt);
            }
        });
        Menu1.add(MenuItemConnect);
        Menu1.add(Separator);

        MenuItemExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Gnome-Process-Stop-32.png"))); // NOI18N
        MenuItemExit.setText("Exit");
        MenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemExitActionPerformed(evt);
            }
        });
        Menu1.add(MenuItemExit);

        MenuBar.add(Menu1);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuItemConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemConnectActionPerformed
    InternalFrameLogin.setVisible(true);
        
        // TODO add your handling code here:                  
    }//GEN-LAST:event_MenuItemConnectActionPerformed

    private void MenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemExitActionPerformed
        // TODO add your handling code here:
        System.exit(0); 
    }//GEN-LAST:event_MenuItemExitActionPerformed
    protected boolean ConnectToFtp(){
        FTPClient ftp = new FTPClient();
        try{
            ftp.connect(TextFieldFtpAddress.getText());
        return true;}catch (Exception ex) {
        return false;}
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyAppGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyAppGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyAppGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyAppGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MyAppGui().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCancel;
    private javax.swing.JDesktopPane DesktopPane1;
    private javax.swing.JInternalFrame InternalFrameLogin;
    private javax.swing.JMenu Menu1;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenuItem MenuItemConnect;
    private javax.swing.JMenuItem MenuItemExit;
    private javax.swing.JPopupMenu.Separator Separator;
    private javax.swing.JTextField TextFieldFtpAddress;
    // End of variables declaration//GEN-END:variables
}
